name: Deploy to production

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    uses: ./.github/workflows/build.yml

  test-e2e-chrome:
    needs: [lint, build]
    uses: ./.github/workflows/test-e2e.yml
    with:
      browser: chrome

  test-e2e-firefox:
    needs: [lint, build]
    uses: ./.github/workflows/test-e2e.yml
    with:
      browser: firefox

  deploy:
    needs: [test-e2e-chrome, test-e2e-firefox]
    uses: ./.github/workflows/firebase-hosting-deploy.yml
    with:
      repoToken: ${{ secrets.GITHUB_TOKEN }}
      firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ALEPOD }}
      channelId: live # Production
