name: Deployment pipeline

# Trigger: on push main
on:
  push:
    branches:
      - main

# Cancel unfinished previous workflow
# github.workflow: Workflow name
# github.ref: Event reference, like branch name. Ex: refs/heads/main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  # lint:
  #   runs-on: ubuntu-22.04
  #   timeout-minutes: 30
  #   steps:
  #     # Get last commit from event branch
  #     # https://github.com/marketplace/actions/checkout
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 1
      
  #     # Install Node
  #     # https://github.com/marketplace/actions/setup-node-js-environment
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         cache: 'npm'
      
  #     # Install dependencies
  #     - name: Install dependencies
  #       run: npm ci

  #      # Lint
  #     - name: Lint app
  #       run: npm run lint

  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      # Get last commit from event branch
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      # Install Node
      # https://github.com/marketplace/actions/setup-node-js-environment
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build
      - name: Build app
        run: npm run build

      # Upload dist folder to use it in test job
      # https://github.com/marketplace/actions/upload-a-build-artifact
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          if-no-files-found: error

  test-e2e-chrome:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    needs: [lint, build]
    steps:
      # Get last commit from event branch
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Download dist folder (Artifact)
      # https://github.com/marketplace/actions/download-a-build-artifact
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
        
      # Install dependencies and cypress. Also start and test app
      # https://github.com/marketplace/actions/cypress-io
      - name: Run tests e2e
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start
          wait-on: http://localhost:3000

  test-e2e-firefox:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    needs: [lint, build]
    steps:
      # Get last commit from event branch
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Download dist folder (Artifact)
      # https://github.com/marketplace/actions/download-a-build-artifact
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
        
      # Install dependencies and cypress. Also start and test app
      # https://github.com/marketplace/actions/cypress-io
      - name: Run tests e2e
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start
          wait-on: http://localhost:3000

  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    needs: [test-e2e-chrome, test-e2e-firefox]
    steps:
      # Get last commit from event branch
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Download dist folder (Artifact)
      # https://github.com/marketplace/actions/download-a-build-artifact
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      
      # Deploy to Firebase Hosting
      # https://github.com/marketplace/actions/deploy-to-firebase-hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ALEPOD }}'
          channelId: live
          projectId: alepod
