name: Deploy to Firebase Hosting (Production)

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/reusable/lint.yml

  build:
    uses: ./.github/workflows/reusable/build.yml

  test-e2e-chrome:
    needs: [lint, build]
    uses: ./.github/workflows/reusable/test-e2e.yml
    with:
      browser: chrome

  test-e2e-firefox:
    needs: [lint, build]
    uses: ./.github/workflows/reusable/test-e2e.yml
    with:
      browser: firefox

  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      # Get last commit from event branch
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Install Node
      # https://github.com/marketplace/actions/setup-node-js-environment
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build
      - name: Build app
        run: npm run build
      
      # Deploy to Firebase Hosting
      # https://github.com/marketplace/actions/deploy-to-firebase-hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ALEPOD }}'
          channelId: live
          projectId: alepod