name: Deploy to Firebase Hosting

on:
  workflow_call:
    inputs:
      repoToken:
        description: Github repository token
        required: true
        type: string
      firebaseServiceAccount:
        description: Firebase service account
        required: true
        type: string
      channelId:
        description: Browser to run tests
        default: ''
        type: string

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      # Get last commit from event branch
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Download dist folder (Artifact)
      # https://github.com/marketplace/actions/download-a-build-artifact
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      
      - name: Display config
        run: echo ${{ inputs.channelId }}
      
      # Deploy to Firebase Hosting
      # https://github.com/marketplace/actions/deploy-to-firebase-hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ inputs.repoToken }}
          firebaseServiceAccount: ${{ inputs.firebaseServiceAccount }}
          projectId: alepod
          channelId: ${{ inputs.channelId }}