name: Lint app

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      # Get last commit from event branch
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      # Install Node
      # https://github.com/marketplace/actions/setup-node-js-environment
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Lint
      - name: Lint app
        run: npm run lint