name: Deployment pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      # Get last commit from repo: https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # Install node v18
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      # Install dependencies
      - name: Install project dependencies
        run: npm install --no-audit --no-fund --no-optional

      # Lint
      - name: Lint app
        run: npm run lint

      # Build
      - name: Build app
        run: npm run build
        
      # Tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start
          wait-on: http://localhost:3000
