name: Test e2e

on:
  workflow_call:
    inputs:
      browser:
        description: Browser to run tests
        default: electron
        type: string

jobs:
  test-e2e:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      # Get last commit from event branch
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Download dist folder (Artifact)
      # https://github.com/marketplace/actions/download-a-build-artifact
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      
      - name: Display config
        run: echo ${{ inputs.browser }}

      # Install dependencies and cypress. Also start and test app
      # https://github.com/marketplace/actions/cypress-io
      - name: Run tests e2e
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          command: npm run test:e2e
          start: npm run start
          wait-on: http://localhost:3000